#!/bin/bash
# WF 2019-04-03
# updated 2024-11-20
imagename=md16o
containername=$imagename
VERSION="0.2"

# Color definitions
blue='\033[0;34m'
red='\033[0;31m'
green='\033[0;32m'
endColor='\033[0m'

# Function to display colored messages
color_msg() {
  local l_color="$1"
  local l_msg="$2"
  echo -e "${l_color}$l_msg${endColor}"
}

# Function to display errors
error() {
  local l_msg="$1"
  color_msg $red "Error:" 1>&2
  color_msg $red "\t$l_msg" 1>&2
  exit 1
}

# Function to display negative messages
negative() {
  local l_msg="$1"
  color_msg $red "❌:$l_msg"
}

# Function to display positive messages
positive() {
  local l_msg="$1"
  color_msg $green "✅:$l_msg"
}

# Function to display usage information
usage() {
  echo "Usage: $0 [OPTIONS]"
  echo "Options:"
  echo "  -h, --help         Show this help message"
  echo "  -b, --bash         Open a Bash session in the Docker container"
  echo "  -d, --debug        Enable debug mode (set -x)"
  echo "  -k, --kill         Stop and remove the Docker container"
  echo "  -r, --run          Run the MagicDraw Docker container"
  echo "  -v, --version      Show version information"
  exit 1
}


# use socat for port 6000
port6000() {
  echo "checking port 6000"
  lsof -i TCP:6000
  if [ $? -ne 0 ]
  then
    socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\"&
  fi
}

# Stop and remove the Docker container if it exists
kill_docker() {
  if docker ps -a --format '{{.Names}}' | grep -q "^$containername$"; then
    color_msg $blue "Stopping and removing existing container: $containername"
    docker stop $containername &>/dev/null
    docker rm $containername &>/dev/null
    positive "Container $containername successfully stopped and removed."
  else
    positive "No existing container with the name $containername found."
  fi
}

# Bash into the Docker container if it exists
bash_docker() {
  if docker ps -a --format '{{.Names}}' | grep -q "^$containername$"; then
    color_msg $blue "Starting a Bash session in the container: $containername"
    docker exec -it $containername /bin/bash
  else
    negative "Container $containername does not exist. Start the container first."
  fi
}

#
# run MagicDraw 16.9 in a docker container
#
run_docker() {
  echo "DISPLAY=$DISPLAY"

  os=$(uname -a)
  case $os in
    Linux*)
     dockerdisplay=$DISPLAY
     n="--net=host"
     v="-v /tmp/.X11-unix:/tmp/.X11-unix -v $HOME/.Xauthority:/root/.Xauthority:rw";;
    Darwin*)
     port6000
     dockerdisplay=docker.for.mac.host.internal:0
     v=""
     n="";;
  esac
  docker run  --name $containername -e DISPLAY=$dockerdisplay $n $v -v $HOME/:/home/$USER bitplan/$imagename:latest
}

# Show usage if no arguments are provided
if [[ $# -eq 0 ]]; then
  usage
fi

# Parse command line arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help) usage ;;
    -b|--bash) bash_docker ;;
    -d|--debug) set -x ;;
    -k|--kill) kill_docker;;
    -r|--run) run_docker;;
    -v|--version) color_msg "Version: $version" ;;
  esac
  shift
done
