#!/bin/bash
# WF 2019-04-03
echo "DISPLAY=$DISPLAY"

# prerequisites
# Check the operating system
os=$(uname -a)

# Install socat if on macOS (Darwin)
if [[ "$os" == *Darwin* ]]; then
  if ! command -v socat &>/dev/null; then
    echo "Installing socat..."
    sudo port install socat
  fi
fi

# use socat for port 6000
port6000() {
  echo "checking port 6000"
  lsof -i TCP:6000
  if [ $? -ne 0 ]
  then
    socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\"&
  fi
}

# Stop and remove the container only if it exists
if docker ps -a --format '{{.Names}}' | grep -q '^javagui$'; then
  echo "Stopping and removing existing javagui container..."
  docker stop javagui
  docker rm javagui
fi

case $os in
  Linux*)
   dockerdisplay=$DISPLAY
   n="--net=host"
   v="-v /tmp/.X11-unix:/tmp/.X11-unix -v $HOME/.Xauthority:/root/.Xauthority:rw";;
  Darwin*)
   port6000
   dockerdisplay=docker.for.mac.host.internal:0
   v=""
   n="";;
esac
docker run  --name javagui -e DISPLAY=$dockerdisplay $n $v bitplan/javagui:latest
